/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fff8f6",
        "surface-dim": "#eed5cb",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff1ec",
        "surface-container": "#ffe9e2",
        "surface-container-high": "#fde3d9",
        "surface-container-highest": "#f7ddd3",
        "on-surface": "#261813",
        "on-surface-variant": "#594137",
        "inverse-surface": "#3c2d27",
        "inverse-on-surface": "#ffede7",
        "outline": "#8d7165",
        "outline-variant": "#e1bfb2",
        "surface-tint": "#a43e00",
        "primary": "#a43e00",
        "on-primary": "#ffffff",
        "primary-container": "#ff6d1f",
        "on-primary-container": "#5b1f00",
        "inverse-primary": "#ffb596",
        "secondary": "#5f5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfde",
        "on-secondary-container": "#636262",
        "tertiary": "#006591",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00a4e9",
        "on-tertiary-container": "#003650",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbcd",
        "primary-fixed-dim": "#ffb596",
        "on-primary-fixed": "#360f00",
        "on-primary-fixed-variant": "#7d2d00",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#474746",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#001e2f",
        "on-tertiary-fixed-variant": "#004c6e",
        "background": "#fff8f6",
        "on-background": "#261813",
        "surface-variant": "#f7ddd3",
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "address-md": ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "xs": "4px",
        "base": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "gutter": "24px",
        "margin": "32px",
        "xl": "40px",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      }
    },
  },
  plugins: [],
}
